-- ============================================================
-- Permite reinserir registros com o MESMO id (necessário p/ restaurar backup).
-- Rode UMA vez no Supabase (SQL Editor). Só afeta como o id é gerado.
-- ============================================================
alter table produtos      alter column id set generated by default;
alter table movimentacoes alter column id set generated by default;
alter table tarefas       alter column id set generated by default;
alter table melhorias     alter column id set generated by default;
